name: Test

on: [push]

jobs:
  test:
    # где запускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
      # выкачиваем репозиторий
      - uses: actions/chekout@v3
      # настраиваем java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # запускаем тесты
      - run: ./gradle clean test